@startuml

interface Post {
    getHeader()
    getBody()
    getLinks()
    getAddressed()
    getCreator()
}

class MessagePost implements Post{
     public MessagePost()
     getHeader()
     getBody()
     getLinks()
     getAddressed()
     getCreator()
}

class EventAdapter implements Post{
    public EventAdapter(Event e)
    //Generate Adapterdata from Event
    getHeader()
    getBody()
    getLinks()
    getAddressed()
    getCreator()
}

class ExerciseUnitAdapter implements Post{
    public ExerciseUnitAdapter(ExerciseUnit e)
    //Generate Adapterdata from ExerciseUnit
    getHeader()
    getBody()
    getLinks()
    getAddressed()
    getCreator()
}

class Event{
    String name
    String information
    Date date
}

class ExerciseUnit{
    String exerciseName
    ArrayList sets
}



class CommunityController{
    public void addPost(Post post)

}

note "How to Use: \n addPost(new EventAdapter(Event));" as ComContNote

ComContNote .. CommunityController

@enduml