@startuml

class JsonObjectRequestBuilder implements Response.Listener, Response.ErrorListener{
  private static String TAG;
  private JsonObjectRequest request;
  private int method = Request.Method.POST;
  private String url;
  private JSONObject jsonObject;
  private Response.Listener<JSONObject> responseListener;
  private Response.ErrorListener errorListener;
  public JsonObjectRequestBuilder(String url)
  public JsonObjectRequestBuilder method(int method)
  public JsonObjectRequestBuilder jsonObject(JSONObject jsonObject)
  public JsonObjectRequestBuilder param(String key, Object value)
  public JsonObjectRequestBuilder responseListener(Response.Listener<JSONObject> responseListener)
  public JsonObjectRequestBuilder errorListener(Response.ErrorListener errorListener)
  public JsonObjectRequest build()
  public void onErrorResponse(VolleyError volleyError)
  public void onResponse(JSONObject jsonObject)
}

@enduml