@startuml

actor APP
control Backend
database Database
database FCM

APP ->> FCM: Request for Token
FCM -->> APP: Token Response

APP ->> Backend: Register Token
Backend ->> Database: Save Token

newpage Send Message

actor APP
control Backend
database Database
database FCM

APP ->> Backend: Send Message with addressed User
Backend ->> Database: Get token of addressed User
Database -->> Backend: Token Response
Backend ->> FCM: Send Message with Token
FCM ->> APP: Send Message

newpage Notification from Server to Client

actor APP
control Backend
database Database
database FCM

Backend ->> Database: Get token of addressed User
Database -->> Backend: Token Response
Backend ->> FCM: Send Notification with Token
FCM ->> APP: Send Notification

@enduml