@startuml


package "Application" {

    package Views{
        [LoginActivity] as LoginA
        [RegisterActivity] as RegisterA
        [MainActivity] as MainA
        [EventActivity] as EventA
        [AGBActivity] as AGBA
        [ChatActivity] as ChatA
    }

    package "ControllerFrontend" {
        [SessionControllerFrontend] as SessionCF
        [EventControllerFrontend] as EventCF
        [ResourceControllerFrontend] as ResourceCF
        [ChatControllerFrontend] as ChatCF
        [PostControllerFrontend] as PostCF
    }
}

cloud {
    [FirebaseCloud] as FBC
}

package "Server" {
    package "Backend" {
        package "ControllerBackend" {
            [SessionControllerBackend] as SessionCB
            [EventControllerBackend] as EventCB
            [ResourceControllerBackend] as ResourceCB
            [ChatControllerBackend] as ChatCB
            [PostControllerBackend] as PostCB
        }
    }

    database "MySQL"{
        ["User"-Table] as USER
        ["AGB"-Table] as AGB
    }

    database "Neo4J"{
        ["Event"-Node] as EVENT
        ["Post"-Node] as POST
    }

    database "MongoDB"{
        ["Message"-Table] as MESSAGE
    }
}


Application -[hidden]down-> FBC
Server -[hidden]up-> FBC

LoginA          <-->        SessionCF
RegisterA       <-->        SessionCF
MainA           <-->        PostCF
EventA          <-->        EventCF
AGBA            <-->        ResourceCF
ChatA           <-->        ChatCF

EventCF          ---->        EventCB
PostCF           ---->        PostCB
SessionCF        ---->        SessionCB
ResourceCF       ---->        ResourceCB
ChatCF           ---->        ChatCB

ChatCF          <-->        FBC
ChatCB           -->        FBC

SessionCB       <-->        USER
ResourceCB      <-->        AGB
EventCB         <-->        EVENT
PostCB          <-->        POST
ChatCB          <-->        MESSAGE

@enduml